### PR TITLE
add support for f2fs on /system + updated flags for all f2fs partitions

### PR DESCRIPTION
**Pull request by FlashingExpert**

### CODE REVIEW

**Comment by Incredible-O** [comment]
Please submit your commits to gerrit.

**Comment by FlashingExpert** [comment]
I did this long time ago, it was not merged...

**Comment by varunchitre15** [comment]
Why you shouldn't use  F2FS on /system ?
1. It doesn't benefit much or safe to say, at all since system partition is read only.
2. After flashing an updated build, it will be reformatted to ext4 anyway.

**Comment by Incredible-O** [comment]
If you push something to gerrit, add me as a reviewer. I don't see everything.

**Comment by FlashingExpert** [comment]
http://review.cyanogenmod.org/?cla_id=on#/c/108437/

**Comment by FlashingExpert** [comment]
1. in case of XL system performance was more snappier than with ext4 even if everyone told me 
   there is no point to do that because read only partition 
   but yeah there is not much difference on highend devices with more cpu cores

**Pull request closed without merging**
